version: "3.1"
services:
  mongodb:
    build: ./mongodb_replica_servers
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
      - MONGO_INITDB_DATABASE=veloz
      - MONGO_REPLICA_HOST=localhost
      - MONGO_REPLICA_PORT=27001
    ports:
      - 27001:27001
